### ISSUE TITLE
Omitting @PrimaryKey causes error

### ISSUE THREAD

**Issue by PhilippS93** [foxylion/rethinkdb-orm-java#1]
When omitting the @PrimaryKey annotation in a model class, a standard key is generated with type String in RethinkDBDAOProcessor.java line 140 with the wrong package name of "java.util.String". It must be java.lang.String. Otherwise, an error is thrown.

cheers ,
Philipp

**Comment by foxylion** [comment]
This is was released with [2.3.0-5](https://github.com/foxylion/rethinkdb-orm-java/releases/tag/2.3.0-5)
